Autopublish releases to npm
IndexCoop/index-coop-smart-contracts pull request #91
Opened 2022-02-02 04:34 UTC by FlattestWhite

2022-02-04 14:36 UTC, 0xModene requested changes
small change needed but mostly looks good

2022-02-04 14:36 UTC, 0xModene commented on package.json
> +  "name": "@indexcoop/index-coop-contracts",
should be 
```typescript
"name": "@indexcoop/index-coop-smart-contracts",
```

2022-02-04 22:35 UTC, FlattestWhite commented on package.json
> +  "name": "@indexcoop/index-coop-contracts",
whoops - fixed

2022-02-04 22:36 UTC, FlattestWhite commented
Just a note on this PR - circle ci atm isn't actually verifying this repo because the yarn.lock wasn't regenerated when porting it over. We cache based on the yarn.lock file. Since the yarn.lock file remains the same, the old build and test steps still pass but its pointing to ~/index-coop-private

2022-02-07 14:04 UTC, 0xModene commented
@FlattestWhite Can you run `yarn` locally and resolve this?

2022-02-08 03:10 UTC, FlattestWhite commented
> @FlattestWhite Can you run `yarn` locally and resolve this?

done

2022-02-08 18:51 UTC, 0xModene approved these changes

2022-02-08 20:00 UTC, merged